"""Data models for the Dream & Distill module.

Defines three core data structures:
- **DreamReport**: result of a memory consolidation cycle
- **WorkflowPattern**: a reusable workflow discovered from session history
- **DistillResult**: the outcome of a workflow-distillation pass
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class DreamReport:
    """Result of a memory consolidation / dream cycle.

    Mirrors the human concept of "sleep -> consolidation":
    noisy, raw memories are processed into structured, durable knowledge.

    Attributes
    ----------
    new_items:
        Number of newly created memory items.
    merged_items:
        Number of duplicate / contradictory pairs that were merged.
    archived_items:
        Number of low-value memories moved to cold storage.
    strengthened:
        Number of high-frequency memories that had their confidence boosted.
    summary:
        Human-readable narrative generated by an LLM (or a simple fallback).
    """

    new_items: int = 0
    merged_items: int = 0
    archived_items: int = 0
    strengthened: int = 0
    summary: str = ""

    def to_dict(self) -> dict:
        """Serialize to a JSON-compatible dict."""
        return {
            "new_items": self.new_items,
            "merged_items": self.merged_items,
            "archived_items": self.archived_items,
            "strengthened": self.strengthened,
            "summary": self.summary,
        }

    def __bool__(self) -> bool:
        """A report is truthy when any work was done."""
        return (
            self.new_items > 0
            or self.merged_items > 0
            or self.archived_items > 0
            or self.strengthened > 0
        )


@dataclass
class WorkflowPattern:
    """A reusable workflow discovered by mining session histories.

    Attributes
    ----------
    name:
        Semantic name assigned by the LLM, e.g. ``"git-sync"``.
    steps:
        Ordered sequence of tool-call descriptors:
        ``[{"tool": "read_file", "args_summary": "...", "duration": 1.2}, ...]``.
    frequency:
        How many times the *exact* sub-sequence appeared in the data.
    confidence:
        Composite score (0.0 - 1.0) based on frequency, consistency,
        and result quality.
    contexts:
        Representative user-intent strings that triggered this pattern.
    avg_duration:
        Mean wall-clock time of the full workflow, in seconds.
    result_quality:
        Fraction of executions that succeeded without error / rollback.
    candidate_type:
        One of ``"skill"``, ``"subagent"``, or ``"alias"``.
    """

    name: str = ""
    steps: list[dict] = field(default_factory=list)
    frequency: int = 0
    confidence: float = 0.0
    contexts: list[str] = field(default_factory=list)
    avg_duration: float = 0.0
    result_quality: float = 0.0
    candidate_type: str = "skill"

    def to_dict(self) -> dict:
        """Serialize to a JSON-compatible dict."""
        return {
            "name": self.name,
            "steps": self.steps,
            "frequency": self.frequency,
            "confidence": self.confidence,
            "contexts": self.contexts,
            "avg_duration": self.avg_duration,
            "result_quality": self.result_quality,
            "candidate_type": self.candidate_type,
        }


@dataclass
class DistillResult:
    """Result of a workflow-distillation pass.

    Patterns are organised into confidence bands so the UI can:
    - Auto-adopt high-confidence candidates.
    - Prompt the user for medium-confidence ones.
    - Silently drop low-confidence noise.
    """

    patterns: list[WorkflowPattern] = field(default_factory=list)
    high_confidence: list[WorkflowPattern] = field(default_factory=list)
    medium_confidence: list[WorkflowPattern] = field(default_factory=list)
    generated_skills: list[Path] = field(default_factory=list)

    def to_dict(self) -> dict:
        """Serialize to a JSON-compatible dict."""
        return {
            "patterns": [p.to_dict() for p in self.patterns],
            "high_confidence": [p.to_dict() for p in self.high_confidence],
            "medium_confidence": [p.to_dict() for p in self.medium_confidence],
            "generated_skills": [str(p) for p in self.generated_skills],
        }
